language: python

dist: bionic

# https://devguide.python.org/#branchstatus
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install flake8 python-coveralls coverage
  - python setup.py bdist_wheel
  - pip install dist/feedgen*

script:
  - make test
  - python -m feedgen
  - python -m feedgen atom
  - python -m feedgen rss

after_success:
   - coveralls
